
#### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "dcl@asdf.com",
  "password": "asdf4"
}

#### Login
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "dcl@asdf.com",
  "password": "asdf4"
}


#### Get users
GET http://localhost:3000/auth/users


### Delete user
DELETE http://localhost:3000/auth/13

### Get one user
GET http://localhost:3000/auth/1


### Query users with email
GET http://localhost:3000/auth?email=d@asdf.com

### Update user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{

  "password": "aaaa"
}

#### Set a color
GET http://localhost:3000/auth/colors/orange


#### Get a color
GET http://localhost:3000/auth/colors